language: r

cache: packages

before_install:
 - cd /home/travis/build/courtiol/IsoriX/IsoriX/

r:
  - oldrel
  - release
  - devel
  
r_check_args: 
  --as-cran

r_packages:
  - covr

addons:
  apt:
    packages:
      - ghostscript
      - libnlopt-dev

after_success:
  - Rscript -e 'library(covr); codecov(type = "examples")'